# This file has been generated by the installer
# $ rails generate platforms:core:install
#
# To change the Network and User class, edit this file.
# It will also be automatically updated when either of the
# following generators are run:
# $ rails generate platforms:core:network [args]
# $ rails generate platforms:core:user [args]

Platforms::Core.configure do |config|
  config.network_class = "Network"
  config.user_class = "User"
end
